export default {
  products: [
    {
      _id: '123',
      name: "Slim Shirt",
      image: "/images/1.jpg",
      price: 460,
      brand: "Nike",
      category: "Shirts",
      countInStock: 0,
    },
    {
      _id: '124',
      name: "Blue Shirt",
      image: "/images/2.jpg",
      price: 260,
      brand: "Nike",
      category: "Shirts",
      countInStock: 7,
    },
    {
      _id: '125',
      name: "Red Shirt",
      image: "/images/3.jpg",
      price: 160,
      brand: "Nike",
      category: "Shirts",
      countInStock: 4,
    },
    {
      _id: '126',
      name: "Slim jeans",
      image: "/images/4.jpg",
      price: 6000,
      brand: "Nike",
      category: "Pants",
      countInStock: 3,
    },
  ],
};
